# Mount the PVC in a Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx
        volumeMounts:
        - name: efs-storage
          mountPath: /mnt/efs
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc


# use commannd:
# kubectl apply -f app-deployment.yaml
