---
- name: with_items usecase
  hosts: all
  # become: true
  tasks: 
    - name: create multiple folder
      file:
        path: /home/user1/folder1
        state: directory

    - name: create multiple folders at a time 
      file:
        path: {{with_items}}
        state: directory
      with_items: 
        - '/home/folder2'
        - '/home/folder2'
        - '/home/folder3'